[package]
name = "east"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sycamore = { version = "0.8", features = ["ssr", "hydrate"] }

east-macro = { path = "macro" }

[workspace]
members = [
  "macro",

  "examples/counter",
]