[package]
name = "east-example-counter-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
sycamore = { version = "0.8", features = ["ssr", "hydrate"] }

east = { path = "../../.." }