[package]
name = "east-example-counter-ui"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
web-sys = "0.3"
wasm-bindgen = "0.2"
serde_json = "1"

east = { path = "../../.." }